let startCalculatingButton = document.getElementById('start'),
    values = document.querySelectorAll( "div[class$='-value']" ),
    importantExpenses = document.getElementsByClassName( 'expenses-item' ),
    importantExpensesConfirmButton = document.getElementsByTagName('button')[0],
    optionalExpensesConfirmButton = document.getElementsByTagName('button')[1],
    calculateButton = document.getElementsByTagName('button')[2],
    optionalExpenses = document.querySelectorAll( '.optionalexpenses-item' ),
    articalsOfPosibleIncomes = document.querySelector('.choose-income-label'),
    checkbox = document.querySelector('input[type="checkbox"]'),
    summ = document.querySelector('input[id="sum"]'),
    percent = document.querySelector('input[id="percent"]'),
    year = document.querySelector('.year-value'),
    month = document.querySelector('.month-value'),
    day = document.querySelector('.day-value');